grails-app/domain/com/unifina/domain/security/IntegrationKey.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2018-02-27-add-id-in-service-to-integration-key.groovy
grails-app/services/com/unifina/service/EthereumIntegrationKeyService.groovy
src/java/com/unifina/api/DuplicateNotAllowedException.java
test/unit/com/unifina/controller/api/IntegrationKeyApiControllerSpec.groovy
test/unit/com/unifina/service/EthereumIntegrationKeyServiceSpec.groovy
test/unit/com/unifina/signalpath/blockchain/EthereumAccountParameterSpec.groovy
test/unit/com/unifina/signalpath/blockchain/SolidityModuleSpec.groovy

- Add database-indexed field `idInService` to `IntegrationKey`. Represents
public identifier of an integration key in the context of the service.
This is equivalent to public wallet address for services ETHEREUM and
ETHEREUM_ID.
- Enforce the uniqueness of public addresses of `IntegrationKey`(s) of type `ETHEREUM_ID` at service level.

Core 1185: Ethereum identity uniqueness

---

.gitignore
grails-app/conf/ApplicationResources.groovy
grails-app/conf/Config.groovy
grails-app/taglib/com/unifina/taglibs/WebpackTagLib.groovy
grails-app/views/dashboard/editor.gsp
grails-app/views/layouts/_layoutHead.gsp
grails-app/views/layouts/main.gsp
grails-app/views/profile/edit.gsp
package-lock.json
package.json
scripts/_Events.groovy
webpack.config.js

- Webpack bundles are now served without interference from Grails resources plugin
- No more problems with Grails not detecting changed resources
- In dev mode, bundles are named `bundleName.bundle.js`
- In prod mode, bundles are named `bundleName.bundle.[hash].js`
- For Grails to know the hashed filenames, some magic was added to `_Events.groovy` which persists those war-build-time filenames to `application.properties`. Those properties automatically appear in `grailsApplication.metadata`.
- `WebpackTagLib` has tags for including the webpack resources in a way that abstracts the complexity of detecting the correct filename.

CORE-1172 webpack bundles no longer handled by grails resources plugin

---

test/functional/ShareSpec.groovy
test/functional/mixins/DashboardMixin.groovy
test/functional/mixins/ListPageMixin.groovy
web-app/react-app/components/DashboardPage/Sidebar/index.jsx
web-app/react-app/components/DashboardPage/Sidebar/sidebar.pcss

- Dashboard sidebar is now scrollable
- Functional tests know to scroll to save button when saving a Dashboard
- Replaced the horrible js hack in ListPageMixin with
```
interact {
moveToElement(row)
}
```

[CORE-1179] Save Button not visible on Dashboard editor if too many canvases shown

---

grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
grails-app/services/com/unifina/service/FreeProductService.groovy
rest-e2e-tests/products-api.js
rest-e2e-tests/streamr-api-clients.js
test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
test/unit/com/unifina/service/FreeProductServiceSpec.groovy
web-app/misc/swagger.json

_Be advised: Basing on feature branch CORE-1257-publish-free-products_
API endpoint `POST /api/v1/products/:productId/undeployFree` for undeploying free Products (price = 0).
- New controller method `ProductApiController#undeployFree`
- New service method `FreeProductService#undeployFreeProduct`
- unit tests for service and controller
- rest e2e tests for endpoint
- swagger for endpoint

CORE-1258: API endpoint for unpublishing free products

---

grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
grails-app/services/com/unifina/service/FreeProductService.groovy
grails-app/services/com/unifina/service/PermissionService.groovy
rest-e2e-tests/products-api.js
rest-e2e-tests/schemas/product.json
rest-e2e-tests/streamr-api-clients.js
rest-e2e-tests/subscriptions-api.js
src/java/com/unifina/api/ProductNotFreeException.java
test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
test/unit/com/unifina/service/FreeProductServiceSpec.groovy
web-app/misc/swagger.json

API endpoint `POST /api/v1/products/:productId/deployFree` for deploying free Products (price = 0).
- New controller method `ProductApiController#deployFree`
- New service `FreeProductService` and method `deployFreeProduct`
- Bring back switch-statement to fix issue with proxy/assist domain classes in `PermissionService#getResourcePropertyName`
- rest e2e tests for endpoint
- swagger for endpoint
- unit tests for service and controller

CORE-1257: API endpoint for publishing free products

---

grails-app/services/com/unifina/service/ProductService.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy

Added callback to `subscriptionService.afterProductUpdated` so that stream permissions get updated after a stream is removed or added to a Product.

CORE-1232: add missing callback

---

grails-app/domain/com/unifina/domain/security/Permission.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2018-04-16-add-ends-at-field-to-permission.groovy
grails-app/services/com/unifina/service/PermissionService.groovy
grails-app/services/com/unifina/service/SubscriptionService.groovy
test/integration/com/unifina/service/PermissionServiceIntegrationSpec.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy
test/unit/com/unifina/service/SubscriptionServiceSpec.groovy

Add support for permissions that expire at a specific point in time. 
- Add field `Date endsAt` to domain class *Permission*
- Database queries of *PermissionService* filter out expired permissions
- Subscription-linked permissions now come attached with an expiration date

CORE-1196: Expiration of subscription-linked permissions

---

grails-app/domain/com/unifina/domain/marketplace/Product.groovy
rest-e2e-tests/products-api.test.js
rest-e2e-tests/schemas/product.json
src/groovy/com/unifina/api/UpdateProductCommand.groovy
test/unit/com/unifina/api/UpdateProductCommandSpec.groovy
test/unit/com/unifina/controller/api/SubscriptionApiControllerSpec.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy

- `Product#toMap` returns `pricePerSecond` as a String instead of a Long
-  Apparently prices can be sent in JSON body as either String or Long, both will be accepted. Thus no changes required on that front.

CORE-1348: pricePerSecond as String

---

grails-app/domain/com/unifina/domain/dashboard/DashboardItem.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2018-04-29-fix-webcomponent-deserialization-bug.groovy
src/java/com/unifina/utils/Webcomponent.java

Domain class `DashboardItem` contains field `webcomponent` of type `Webcomponent`, which is an Enum. When GORM loads a `DashboardItem` from the database it loads the associated `webcomponent` by deserializing a string stored in the database (via `Enum#valueOf(String`). These strings are produced to the database by `Webcomponent#toString()`. However, in this particular case, the method was overridden to produce a different string compared to the default behavior of `Enum#toString`. Thus de-serialization fails.
The bug is exemplified by `canvas.refresh()` at Line 94 of `CanvasApiController#stop`. Hypothesis: apparently refreshing a domain class causes associated domain classes to be loaded in as well, and because `Canvas` `hasMany` `DashboardItem`, dashboard items get loaded when canvas is …

CORE-1267: fix Webcomponent deserialization bug

---

grails-app/conf/Config.groovy
grails-app/controllers/com/unifina/controller/security/RegisterController.groovy
grails-app/views/register/signup.gsp

Captcha on signup can now be enabled/disabled via a configuration option. It is now **disabled** by default. The reason is that we are using Google reCaptcha and that is blocked by the Chinese firewall, so Chinese can't sign up without VPN.

CORE-1357 remove captcha from signup by default

---

grails-app/controllers/com/unifina/controller/help/HelpController.groovy

Make API and user guide documentation public.
Tested by hand that
- Works when not logged in
- Works when logged in (and API key is included in Swagger)

CORE-1330: Make API and user guide documentation public

---

grails-app/services/com/unifina/service/StreamService.groovy

Start incrementing kafka offsets from [Number.MIN_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER) instead of `Long.MIN_VALUE` when uploading a CSV file to Streamr. This ensures that the the values are not truncated by JavaScript (in Data API and/or browser) thereby causing events to seemingly have the same offset -9223372036854776000.

CORE-1175: Fix CSV importing offset issue

---

grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
grails-app/services/com/unifina/service/ProductService.groovy
test/unit/com/unifina/service/ProductServiceRelatedProductsSpec.groovy
test/unit/com/unifina/service/RelatedProductsSpec.groovy

- Fix inifinite loop in `ProductService#relatedProducts`, see comment in "Files changed".
- Respond with `Product#toSummaryMap()` instead of `Product`.
- Add `publicAccess=true` to fetches inside `ProductService#relatedProducts` to make sure that results are returned.
- Some refactorings

CORE-1378: fix infinite loop in related products

---

grails-app/services/com/unifina/service/ApiService.groovy
src/groovy/com/unifina/api/ListParams.groovy
test/unit/com/unifina/api/ListParamsSpec.groovy
test/unit/com/unifina/service/ApiServiceSpec.groovy
web-app/misc/swagger.json

Add url parameter `grantedAccess` to API listing endpoints. When set to `false`, API endpoint will respond with a result set that exclude resources that are not publicly available.

CORE-1375: add grantedAccess to ListParam

---

grails-app/services/com/unifina/service/PermissionService.groovy
test/integration/com/unifina/service/PermissionServiceIntegrationSpec.groovy
test/unit/com/unifina/controller/api/StreamApiControllerSpec.groovy
test/unit/com/unifina/controller/security/RegisterControllerSpec.groovy
test/unit/com/unifina/service/DashboardServiceSpec.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy
test/unit/com/unifina/service/UserServiceSpec.groovy

Addresses issue in which a resource can appear several times in the JSON response list produced by an API endpoint.
If a user has two or more permissions with the same access-level (e.g. ` Operation.READ`) to a resource, the resulting list of resources produced by `apiService#list` and `permissionService#createUserPermissionCriteria` will contain that resource multiple times. The desire is that a resource appear at maximum once per results (even across pagination).
This was fixed by modifying the database query that Grails produces. By grouping the `permission` table by resource id (e.g. `canvas_id`, `dashboard_id`, `stream_id` etc.) we ensure that a resource appear at most once in the result set before joining with the resource database table. 
Unfortunately changes had to be made to …

CORE-1346: Duplicate results returned by API listing endpoints

---

test/integration/com/unifina/com/unifina/domain/marketplace/PaidSubscriptionIntegrationSpec.groovy

I was worried that case-sensitivity issues could cause problems when matching the Ethereum addresses of `PaidSubscription` to those of `IntegrationKey`. Then I (re-)learned that MySQL is by default case-insensitive with respect to strings. Therefore string matching in `WHERE` clause and uniqueness constraints are case-insensitive so no problems arise!
Anyway I thought it would be a good idea to encode this assumptions as tests just in case there were any changes to our environment in the future and this property would no longer hold.

CORE-1384: test subscription case-insensitivity

---

grails-app/controllers/com/unifina/controller/core/signalpath/CanvasController.groovy
grails-app/views/canvas/editor.gsp

Currently has an issue (on my very local dev env at least) that the correct canvas only flashes by, is replaced with empty canvas. Might have something to do with the tour being active.
Henri marked as reviewer mostly to comment on why request.JSON is in canvas/editor controller code (it should be a GET, without body, so what should request.JSON be and when?)

CORE-1226: query params addModule and addStream to /canvas/editor

---

.idea/misc.xml

Use SDKMAN to install correct Oracle JDK 1.8:
% sdk use java 8.0.171-oracle

chore: Use production JDK in development env

---

grails-app/conf/BuildConfig.groovy
grails-app/services/com/unifina/service/SignalPathService.groovy
src/java/com/unifina/exceptions/UnauthorizedStreamException.java
src/java/com/unifina/signalpath/SignalPath.java

now checked SHALLOWLY upon starting. Can still be circumvented by taking it as subcanvas. These problems should vanish once data points are checked against stream permissions.

CORE-1414: Should not be able to start a canvas if it has a Stream without permission

---

grails-app/conf/com/unifina/filters/UnifinaCoreAPIFilters.groovy
src/java/com/unifina/security/AllowRole.java
src/java/com/unifina/security/AuthenticationResult.java
src/java/com/unifina/security/StreamrApi.java
test/unit/com/unifina/security/AllowRoleSpec.groovy
test/unit/com/unifina/security/AuthenticationResultSpec.groovy

`@StreamrApi` annotation now supports role requirements. By default everything works as before (no roles are required.) 
Usage:
```
@StreamrApi(authenticationLevel = AuthLevel.USER, allowRoles = AllowRole.DEVOPS)
```
or with multiple roles (of which at least one must be satisfied by logged-in user)
```
@StreamrApi(authenticationLevel = AuthLevel.USER, allowRoles = [AllowRole.DEVOPS, AllowRole.ADMIN])
```
Note that `authenticationFilter` has not been (unit) tested in this PR. The reason is that in Grails there are no tools to really unit test a filter by itself, but rather this is done in the context of writing a unit test for a controller that uses the filter. We should make sure that the functionality gets tested when writing first controller that uses role requirements with the …

CORE-1332: add role checking to StreamrApi-annotation

---

src/java/com/unifina/datasource/DataSourceEventQueue.java
src/java/com/unifina/feed/StreamrMessage.java
src/java/com/unifina/signalpath/SignalPathRunner.java

- remove (unused) catch-up functionality from `AbstractFeedProxy`
- add hard limit to the size of `DataSourceEventQueue#queue` as a precaution to avoid the queue from growing without bound. 
- make sure that the `RedisFeed` of a crashed `SignalPath` gets properly cleaned up so as to avoid leaking memory.

Fix memory leak issue

---

.idea/misc.xml
grails-app/controllers/com/unifina/controller/security/LoginRedirectValidator.groovy
src/java/com/unifina/security/RedirectAppendingAuthenticationEntryPoint.java
test/unit/com/unifina/security/RedirectAppendingAuthenticationEntryPointSpec.groovy

Check for presence of `X-Forwarded-*` headers written by load balancers, and use that to build the redirect url. Otherwise the redirect url ends up with `http://tomcat/...` written by nginx, which doesn't pass redirect url validation.

[CORE-1482] Redirect after a protected route not working

---

grails-app/conf/Config.groovy

Enables user to edit their name, timezone & change their password via API calls. Required for new editor frontend. 
Related to both `EDITOR-8` & `EDITOR-9`.

Enable CORS for /profile/* endpoints

---

grails-app/services/com/unifina/service/SignalPathService.groovy
test/unit/com/unifina/service/SignalPathServiceSpec.groovy

Noticed that unauthenticated runtime requests to canvases are broken, and fixed it while at it. The bug was a regression from [this commit](https://github.com/streamr-dev/engine-and-editor/commit/c08f8b58c6c21615728e58a8a63e7e8f0d2edaa3).

Add null-safety to accessing user object in buildRuntimeRequest

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/CanvasApiController.groovy
src/groovy/com/unifina/api/StartCanvasAsAdminParams.groovy
test/unit/com/unifina/controller/api/CanvasApiControllerSpec.groovy

Allow admin to start any canvas as any user via admin-only API endpoint.

CORE-1470: API endpoint to start canvas as admin

---

grails-app/domain/com/unifina/domain/security/IntegrationKey.groovy
src/java/com/unifina/signalpath/blockchain/EthereumAccountParameter.java

was added in https://github.com/streamr-dev/engine-and-editor/commit/eef4def20807d3a71259d83b343cc34051a99368 but modified in https://github.com/streamr-dev/engine-and-editor/commit/88cef228c4319d5baea4ffbef9fb5a30b27db82c, now re-adding the first fix, just to see if it helps. This is an old problem with lazy loading of IntegrationKey domain object.

CORE-1550: Re-add old fix, try eager fetching

---

grails-app/views/layouts/_topnav.gsp
web-app/js/unifina/dashboard/dashboard-editor.js
web-app/js/unifina/module-browser/module-browser.js
web-app/js/unifina/signalPath/core/Endpoint.js
web-app/js/unifina/signalPath/core/IOSwitch.js
web-app/js/unifina/signalPath/core/Input.js
web-app/js/unifina/signalPath/core/Parameter.js
web-app/js/unifina/signalPath/generic/emptyModule.js
web-app/js/unifina/signalPath/specific/chartInput.js
web-app/js/unifina/signalPath/specific/commentModule.js
web-app/js/unifina/signalPath/specific/gaugeModule.js
web-app/js/unifina/signalPath/specific/solidityModule.js
web-app/js/unifina/stream-fields/stream-fields.js
web-app/js/unifina/streamr-chart/streamr-chart.js
web-app/js/unifina/streamr-switcher/streamr-switcher.js
web-app/js/unifina/streamr-table/streamr-table.js

- Changed `$(elementAsHtml)` to `$(tagName, attributes)` where necessary (basically where there was any variable injections. Example:
```
// old
var element = $("<div attr1="foo"><a attr2="bar">" + content + "</a></div>")
// new
var a = $('<a/>', {
attr2: 'bar',
text: content, // attribute text is escaped by jQuery
})
var element = $('<div/>', {
attr1: 'foo',
}).append(a)
```
- Change occurences of `$el.html(text)` to `$el.text(text)` (`.text()` escapes the content) where `.html()` cleary was not needed
- Change occurences of `$el.html(jQueryElement)` to `$el.empty().append(jQueryElement)`
I went through the features with changed code but would also appreciate if someone else tried them as well:) (eg. `.append('<div/>', { ... })` instead of `.append($('<div/>', { ... })` ignores the …

[CORE-1554] Javascript injection vulnerability in old Editor

---

grails-app/controllers/com/unifina/controller/security/ProfileController.groovy
grails-app/views/profile/edit.gsp
test/unit/com/unifina/controller/security/ProfileControllerSpec.groovy

A security researcher discovered a bug in the old `ProfileController#update` action, which allowed the username to be changed. This bug combined with CSRF vulnerability enables an attacker to take over accounts by tricking a user into a malicious site while they are logged in, and then making a request to the faulty endpoint.
- This update only fixes the bug in the endpoint. The app still remains vulnerable to CSRF attacks in general (no other ways to exploit it with critical consequences are currently known).
- The new single-page app, once released, will use token-based sessions instead of cookie-based sessions. That will be the ultimate fix to CSRF. Probably not worth it to ship a full CSRF fix to the old app anymore.

profile/update endpoint can't update username anymore

---

web-app/react-app/components/ProfilePage/IdentityHandler/index.jsx
web-app/react-app/tests/utils/web3Provider.test.js
web-app/react-app/utils/web3Provider.js

Requesting permission to read the account information from the Metamask Provider, to be compliant with the upcoming breaking change coming from the Metamask extension. Since this will be washed away in the coming weeks with the new userpages, not much time was spent on the UX.
Affects: Profile Page Settings
Behaviour: 
New Metamask client:
Old Metamask behaviour:
No change
https://github.com/MetaMask/metamask-extension/pull/4703
https://eips.ethereum.org/EIPS/eip-1102

[CORE-1564] - Request Metamask Account Permission (profile settings page)

---

src/java/com/unifina/feed/redis/MultipleRedisMessageSource.java
src/java/com/unifina/feed/redis/RedisMessageSource.java
test/integration/com/unifina/service/RunCanvasSpec.groovy

**Why it broke**
After some binary protocol refactoring in #528, `StreamrBinaryMessageWithKafkaMetadata` is no longer a subclass of `StreamrBinaryMessage`, but instead the former contains the latter.
`StreamrBinaryMessageParser` expects `StreamrBinaryMessage`s as input - a condition previously fulfilled by both `StreamrBinaryMessageWithKafkaMetadata` and `StreamrBinaryMessage` due to inheritance, but after the refactor the class would not accept `StreamrBinaryMessageWithKafkaMetadata` anymore, failing only at runtime due to some generics at play.
**Why it wasn't caught by tests**
Integration test `RunCanvasSpec` tests that the overall message pipeline is working, but for some reason it was `@Ignore`d in [this commit](https://github.com/streamr-dev/engine-and-editor/commit/34a11beb4ef3de7c1 …

Fix message parsing regression in master

---

grails-app/services/com/unifina/service/NodeService.groovy
grails-app/services/com/unifina/service/SignalPathService.groovy
src/java/com/unifina/datasource/DataSource.java
src/java/com/unifina/signalpath/ModuleWithUI.java
src/java/com/unifina/signalpath/SignalPathRunner.java
test/integration/com/unifina/service/RunCanvasSpec.groovy
travis_scripts/integration_test.sh

Bring back `RunCanvasSpec`, which was originally `@Ignore`d by @harbu months ago due to troubles on Travis.
Two bugs were found and fixed:
- `RunCanvasSpec` was transactional and ended up blocking database transactions executed by the system under test
- Kafka didn't work due to the equivalent of `streamr-docker-dev bind-ip` missing from Travis config

WIP: Fix RunCanvasSpec

---

.travis.yml
Dockerfile.stg

-  Build war without test flag
The CI environment will run the docker version of the platform and the same image should then be used for production deployments(just a different war), Our current use-case only supported the developer experience with Docker now we are adding the staging step.

feat: DEVOPS-20 - Staging/CI Docker environment:

---

web-app/misc/swagger.json

Some fixes and downgrades to the definition file in this PR to allow for compatibility with the [API-Explorer](https://github.com/streamr-dev/api-explorer).
If these changes are too much of a roll-back, then it may be better to keep two versions of the definition file moving forward - one kept at Version 2 of the open API standard and one allowed to be at the bleeding edge (Version 3 currently).
The explorer is only compatible with V2.
List of changes:
- type: dateTime -> date-time https://swagger.io/specification/
- Changed ID type from Integer to String in the case of Canvas IDs and Dashboard IDs as these IDs contain letters. Not strictly needed, but helped with HTML5 validation of these inputs in the explorer.
- 'All-of' uses removed - it is a V3 feature
- Some parameter REFs needed to …

CORE-1614: Swagger API Definition Compatibility Updates

---

grails-app/conf/UrlMappings.groovy

Adding method to UrlMappings enables several HTTP methods for one endpoint. Current mappings are:
- GET "/api/v1/users/me"
- PUT "/api/v1/users/me"
- DELETE "/api/v1/users/me"

fix: GET/PUT/DELETE /api/v1/users/me

---

.idea/codeStyles/Project.xml
.idea/misc.xml
src/java/com/unifina/data/StreamPartitioner.java
src/java/com/unifina/signalpath/utils/MessageChainUtil.java
test/unit/com/unifina/data/StreamPartitionerSpec.groovy

Replace the murmur3 hash function with md5 when converting `partitionKey` to `streamPartition` to reflect the same changes made in the JS and Java clients.

replace murmur3 with md5

---

grails-app/conf/Config.groovy
src/java/com/unifina/signalpath/blockchain/EthereumCall.java
src/java/com/unifina/signalpath/blockchain/EthereumModuleOptions.java
src/java/com/unifina/signalpath/blockchain/GetEvents.java
src/java/com/unifina/signalpath/blockchain/SendEthereumTransaction.java
src/java/com/unifina/signalpath/blockchain/SolidityCompileDeploy.java
src/java/com/unifina/signalpath/blockchain/SolidityModule.java
src/java/com/unifina/signalpath/blockchain/Web3jHelper.java
test/unit/com/unifina/signalpath/blockchain/SendEthereumTransactionSpec.groovy
test/unit/com/unifina/signalpath/blockchain/SolidityCompileDeploySpec.groovy
test/unit/com/unifina/signalpath/blockchain/SolidityModuleSpec.groovy

Handle the situation where a tx receipt is not immediately available after submitting a transaction to an Ethereum node to deploy a contract. Old code often produced NPE. New code retries periodically until tx receipt is non-null or max retries is reached.
There should be a test for this, but I don't have time to add it right now. @isentropy please feel free to contribute a test.
If the beta launch draws nearer and we want to merge this without adding a test, we can create a technical debt ticket to add the test later.

Retry transaction receipt

---

grails-app/services/com/unifina/service/CassandraService.groovy

Method `StreamApiController#status` invokes `getLatestStreamMessage` to fetch the latest stream message from Cassandra. In many cases, such as the tram demo, the query times out in production. Put in an extra `ts >= now - 1 year` condition to avoid having to sort the entire result set of a stream/partition-pair. Or at least this prevents the query from not timing out.
Tested locally that this doesn't break the status API endpoint.

CORE-1724: CassandraService: limit in getLatestStreamMessage

---

grails-app/services/com/unifina/service/StreamService.groovy

For whatever reason (perhaps a bug in GORM?) doing the same query in a different way does not cause MySQLSyntaxErrorException.

CORE-1744: fix MySqlSyntaxErrorException

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/StreamApiController.groovy
grails-app/services/com/unifina/service/StreamService.groovy
test/unit/com/unifina/controller/api/StreamApiControllerSpec.groovy
test/unit/com/unifina/service/StreamServiceSpec.groovy

This new endpoint will be used by the streamr-client during the key exchange for encryption. Before sending the group key encrypted with the subscriber's RSA public key, the publisher first verifies that the request comes from a valid subscriber by checking the list of subscribers using this endpoint.
This endpoint is very similar to "streams/${id}/publishers".

create streams/${id}/subscribers endpoint

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/StreamApiController.groovy
grails-app/services/com/unifina/service/StreamService.groovy
test/unit/com/unifina/controller/api/StreamApiControllerSpec.groovy
test/unit/com/unifina/service/StreamServiceSpec.groovy

2 new endpoints to check if an Ethereum address is a valid publisher/subscriber. Uses HTTP codes 200 and 404 as responses.
This is needed to optimise both signature verification and the key exchange mechanism.

add endpoints and tests

---

src/java/com/unifina/signalpath/blockchain/ContractEventPoller.java
src/java/com/unifina/signalpath/blockchain/EthereumJsonRpc.java
src/java/com/unifina/signalpath/blockchain/EthereumModuleOptions.java
src/java/com/unifina/signalpath/blockchain/EventsListener.java
src/java/com/unifina/signalpath/blockchain/GetEvents.java
src/java/com/unifina/signalpath/blockchain/HttpEthereumJsonRpc.java
src/java/com/unifina/signalpath/blockchain/JsonRpcResponseHandler.java
src/java/com/unifina/signalpath/blockchain/WebsocketEthereumJsonRpc.java

This PR allows GetEvents to poll event data over websockets instead of http. This is necessary to get event data from Infura nodes, which only support filters over websockets. Here are the major changes:
- I renamed EthereumJsonRpc as HttpEthereumJsonRpc and created a new class WebsocketsEthereumJsonRpc, Both HttpEthereumJsonRpc and WebsocketsEthereumJsonRpc  extend a common abstract base class EthereumJsonRpc. WebsocketsEthereumJsonRpc and HttpEthereumJsonRpc can be easily interchanged.
- rpcCall() no longer returns the RPC response, which is instead handled by an interface JsonRpcResponseHandler that is passed to the EthereumJsonRpc constructor. In the case of WebsocketsEthereumJsonRpc, the handler is called by another thread when the response arrives. In the case of …

Core 1723 infura websockets

---

src/java/com/unifina/signalpath/blockchain/SendEthereumTransaction.java

I was using `SendEthereumTransaction` a bit. I noticed that if an error occurs (in my case, insufficient ETH for gas), the module will still attempt to send out (at least) the tx hash, which in my case is `null` and causes an exception.

Fix invalid send in case of tx error

---

grails-app/views/emails/_email_share_invite.gsp

Email looks like this:
I changed Streamr Core link to point to https://www.streamr.com/core/

CORE-1778: Improve canvas sharing email message

---

grails-app/controllers/com/unifina/controller/api/ErrorController.groovy
src/groovy/com/unifina/api/UpdateProductCommand.groovy
src/java/com/unifina/api/FieldCannotBeUpdatedException.java
test/unit/com/unifina/api/UpdateProductCommandSpec.groovy

After chatting with @juhah, I went through the backend code related to updating `Product` objects, and tweaked and clarified it a little:
- The backend now throws if the user tries to change any of the on-chain fields of deployed paid products. This will help the front-end devs by informing they're trying to do something illegal.
- When updating a deployed paid product, the frontend can avoid the exception by either omitting the on-chain fields completely, or providing values equal to the old values. Neither approach will trigger the exception.
To summarize, the rules are:
- Updating on-chain fields of `DEPLOYED` paid products is always illegal.
- Updating off-chain fields is always allowed.
- Updating all fields of `NOT_DEPLOYED` products is always allowed.
- Updating all fields of free …

Clarify allowed and disallowed product updates to the database

---

src/java/com/unifina/signalpath/blockchain/SolidityCompileDeploy.java
test/unit/com/unifina/signalpath/blockchain/SolidityCompileDeploySpec.groovy

- Compile button works when no account is selected in SolidityCompileDeploy, So you can see if your code compiles, but not much else. I think a [copy ABI button](https://streamr.atlassian.net/browse/PLATFORM-1023) would be useful here to copy the generated ABI into a GetContractAt module.
- Compile shows errors in this case
- Deploy throws an exception when no account selected. I think it should be **disabled** if no Ethreum account is selected. Why show an option that just throws an error?

CORE-1794-compile-without-account

---

grails-app/conf/Config.groovy
grails-app/conf/com/unifina/filters/UnifinaCoreAPIFilters.groovy
grails-app/controllers/com/unifina/controller/api/ErrorController.groovy
grails-app/services/com/unifina/service/CommunityJoinRequestService.groovy
grails-app/services/com/unifina/service/StreamrClientService.groovy
src/java/com/unifina/signalpath/blockchain/ContractEventPoller.java
src/java/com/unifina/signalpath/remote/AbstractHttpModule.java
test/integration/com/unifina/service/CommunityJoinRequestServiceIntegrationSpec.groovy
test/unit/com/unifina/controller/api/ErrorControllerSpec.groovy
test/unit/com/unifina/service/CommunityJoinRequestServiceSpec.groovy

- Reduce noise from `AbstractHttpModule` and `ContractEventPoller`
- Cleanup code related to exception logging
- Only log unexpected exceptions (status code `500` basically) to reduce noise
- Add debug logging to `CommunityJoinRequestService` and `StreamrClientService`
- Turn on debug logging for above classes and `StreamrClient` to debug join issues in production
This PR includes PR #682.

Logging tweaks

---

src/java/com/unifina/signalpath/remote/AbstractHttpModule.java
src/java/com/unifina/signalpath/remote/Http.java

Hi guys,
I wanna use the HTTP module for public site's blog section. The problem is that it doesn't handle non-JSON responses very well. I've managed to squeeze the first 13 bytes out of the body of what's clearly an XML but that's all. And it's also kinda weird that our JSON parser lets it be, at all. 13 bytes? A bit confusing. Here's an example of the "13":
_URL: https://medium.com/feed/streamrblog_
—
Anyway, in this PR I add another parameter to the HTTP module aiming at making it more useful. I named it `dataType`. It starts off being set to `auto` which more or less mimics the previous behaviour. Next to it stands: `json`, `text` and `binary`. Here's what I initially expected to see (which now works!):
So, in short, use
- `auto` for the previous behaviour,
- `binary` to get what …

Add `dataType` to HTTP module

---

src/java/com/unifina/feed/util/IterableMessageHandler.java

Production log is currently full of `2019-10-21 11:19:39,901 [Timer-550] ERROR util.IterableMessageHandler  - onMessage: the queue is full and no space was made within 10 sec. The message will be dropped.`

Add logging to see which stream is causing problems

---

grails-app/domain/com/unifina/domain/security/Permission.groovy
grails-app/services/com/unifina/service/PermissionService.groovy
test/integration/com/unifina/service/PermissionServiceIntegrationSpec.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy

If a user has certain permissions to a canvas, he should also have those same permissions to the UI channel streams of that canvas.
Currently, the `/streams/:streamId/permissions/me` endpoint does not list those transitive permissions for UI channel streams. See the [JIRA ticket](https://streamr.atlassian.net/browse/CORE-1825).
I started working on a fix, but got stuck with some weird behavior of the unit test. Unrelated permissions were being returned by the criteria query. @harbu or @kare please take this over and see if you can get the test working. I probably can't put more work into this before MozFest.

Fix UI channel transitive permissions

---

docker/Dockerfile.dev

Fix smtp hostname to be `smtp` so signup emails and email module etc. can be sent from docker environment.

Dockerfile.dev: fix SMTP hostname

---

src/java/com/unifina/signalpath/blockchain/ContractEventPoller.java
src/java/com/unifina/signalpath/blockchain/GetEvents.java
src/java/com/unifina/signalpath/blockchain/WebsocketEthereumJsonRpc.java

This PR has the bugfixes from https://github.com/streamr-dev/engine-and-editor/pull/696, without the Ethereum modules refactor that Juuso did. 
Contains the following bugfixes:
1. fixed bug where 0 parameter event was always sent, even if another event was triggered.
2. RuntimeException caught in WebsocketEthereumJsonRpc.openConnectionRetryIfFail(). DNS lookup failure causes a RuntimeException, which wasn't caught.
3. InterruptedException caught when sleeping between connection retries. I'm not sure why thread was interrupted, but I've seen this in E&E.
4. No RuntimeExceptions thrown when polling to closed WS. This happens when ContractEventPoller polls the RPC while the websocket is closed and attempting reopen.

Getevent bugfixes minimal pr 20191105

---

src/java/com/unifina/signalpath/blockchain/SendEthereumTransaction.java

web3j library converts to uint using longValue() when passed floating point args. So args greater than MAX_LONG are clipped. This promotes floating point args to BigDecimal, which are converted to uint via toBigInteger()

promote double and float to BigDecimal when calling web3j function

---

.idea/engine-and-editor-grailsPlugins.iml
.idea/engine-and-editor.iml
grails-app/conf/BuildConfig.groovy

Bump `com.streamr.client` to 1.2.1. Tested by hand and looks like it fixes issue in which canvases drop subscriptions to streams during broker downtime.

bump com.streamr.client to 1.2.1 to fix canvases dropping subscriptions during broker downtime

---

grails-app/controllers/com/unifina/controller/api/CommunitySecretApiController.groovy
grails-app/domain/com/unifina/domain/community/CommunitySecret.groovy
test/unit/com/unifina/controller/api/CommunitySecretApiControllerSpec.groovy

Main rationale here is: admin access control is enforced already for all endpoints. What's the point of forcing the front-end to do multiple HTTP queries?

Show secrets also in full listing

---

grails-app/services/com/unifina/service/CommunityOperatorService.groovy
test/unit/com/unifina/service/CommunityOperatorServiceSpec.groovy

```
2019-11-18 11:30:57,447 [http-nio-8080-exec-68] ERROR api.ErrorController  - Unexpected error occurred on request to GET http://tomcat/grails/error/index.dispatch, returning status code 500
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:286)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at …
```

CORE-1846: Fix ConnectionPoolTimeoutException

---

rest-e2e-tests/canvas-api.test.js
rest-e2e-tests/test-data/canvas-api.test.js-canvas-clock.json
rest-e2e-tests/test-data/canvas-api.test.js-canvas.json
src/java/com/unifina/data/HistoricalEventQueue.java
src/java/com/unifina/datasource/DataSourceEventQueue.java
test/unit/com/unifina/datasource/DataSourceEventQueueSpec.groovy

Timestamps smaller than the initial value of `globals.time` were being reported to `ITimeListener`s in realtime mode. This lead to problems in case time listeners (such as the `Clock` module) read time when the module is initialized, because the first reported clock tick was less than the time at initialization.
This PR includes a slight refactoring to start the time ticking from the next full second that follows the initial value of `globals.time`.
This PR is an alternative solution to #711 by @harbu, which requires modules to guard against the bug in time reporting. Assuming that this PR does indeed fix the underlying bug, the modules don't need to guard against this issue anymore.
@timoxley 's tests added in #707 seem to pass with this branch. Would be good if you guys could do some …

Fix time reporting in DataSourceEventQueue

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/PermissionApiController.groovy
grails-app/services/com/unifina/service/PermissionService.groovy
test/unit/com/unifina/controller/api/PermissionApiControllerSpec.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy

Admin endpoint to clean up expired permissions (`endsAt` is in the past).

Core 1861 perms cleanup

---

grails-app/conf/BuildConfig.groovy

There are some intermittent download errors with repo1.maven.org at the moment. I expect them to resolve automatically. This patch uses HTTPS to access repo1.maven.org.
repo1.maven.org will drop HTTP support on 15th of Jan.

Use HTTPS instead of HTTP for Maven repo

---

scripts/entrypoint.sh

Add `nodePrivateKey` parameter with value from environment variable `ETHEREUM_NODE_PRIVATE_KEY`.
Is this enough to enable setting value in docker-compose.yml?

Add streamr.ethereum.nodePrivateKey parameter to entrypoint.sh

---

grails-app/services/com/unifina/service/CassandraService.groovy

Currently these queries seem to timeout a lot in Cassandra and may cause impact on broker service reliability. Let's test out reducing the result set of the query if this helps with timeouts.

hotfix: reduce CassandraService query from 1 year to 1 week

---

grails-app/controllers/com/unifina/controller/api/ErrorController.groovy
grails-app/services/com/unifina/service/CommunityOperatorService.groovy
src/java/com/unifina/api/ApiError.java
src/java/com/unifina/api/CsvParseUnknownSchemaException.java
src/java/com/unifina/api/InvalidArgumentsException.java
src/java/com/unifina/api/NotFoundException.java
src/java/com/unifina/api/NotPermittedException.java
src/java/com/unifina/api/ProxyException.groovy
test/unit/com/unifina/service/CommunityOperatorServiceSpec.groovy

TODO still to check timeouts (can be as low as 1 sec) and connection queue capacity (can be as small as 100 or even 10 concurrent pending connections).
Hand-tested working (no integration test to extend):
```
$ curl -v http://localhost:8081/streamr-core/api/v1/communities
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8081 (#0)
> GET /streamr-core/api/v1/communities HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Server: Apache-Coyote/1.1
< Retry-After: 60
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Mon, 13 Jan 2020 11:53:27 GMT
< Connection: close
<
* Closing connection 0
{"code":"PROXY_ERROR","message":"Community server is busy or not responding"}
```

CORE-1863: change PROXY_ERROR to 503 if CPS is not responding

---

grails-app/conf/BuildConfig.groovy

CORE-1892: Remove Grails plugin cache-headers 1.1.7

---

grails-app/services/com/unifina/service/StreamrClientService.groovy
test/integration/com/unifina/service/StreamrClientServiceSpec.groovy

Makes `StreamrClientService#getInstanceForThisEngineNode()` thread-safe

Hotfix: Make StreamrClientService thread-safe

---

grails-app/services/com/unifina/service/DataUnionOperatorService.groovy

Requests that get proxied to DUS currently start database transactions, because by default Grails service methods are transactional. There is no need to consult the database when forwarding requests, so disable the default behavior by setting `transactional = false`.

Hotfix: Make DataUnionOperatorService non-transactional

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/StreamApiController.groovy
grails-app/domain/com/unifina/domain/data/Stream.groovy
rest-e2e-tests/streamr-api-clients.js
rest-e2e-tests/streams-api.test.js

Make the fields necessary for message validation public (=no authentication required). In the future these fields would be on-chain, so public anyway.
Add a new public endpoint `/streams/{id}/validation` that returns only the following fields of a `Stream`:
- `partitions`
- `requireSignedData`
- `requireEncryptedData`
Additionally, make public the endpoints necessary to check valid publishers/subscribers:
- `/streams/{id}/publishers`
- `/streams/{id}/subscribers`
- `/streams/{id}/publisher/{address}`
- `/streams/{id}/subscriber/{address}`

CORE-1918 validation endpoints

---

grails-app/services/com/unifina/service/StreamrClientService.groovy
src/java/com/streamr/client/authentication/InternalAuthenticationMethod.java
test/integration/com/unifina/service/StreamrClientServiceIntegrationSpec.groovy

Avoids making an API call to the system itself when creating the `StreamrClient` for the EE instance. This can lead to a deadlock when lots of DU join requests are coming in during instance startup.
Re the TODO: The code can be made slightly prettier when [this PR](https://github.com/streamr-dev/streamr-client-java/pull/50) is merged and Java client updated. But it's not terribly hacky as is.

Use InternalAuthenticationMethod to obtain sessionToken

---

grails-app/services/com/unifina/service/StreamrClientService.groovy
src/java/com/streamr/client/authentication/InternalAuthenticationMethod.java
src/java/com/unifina/utils/testutils/FakeStreamrClient.java
test/integration/com/unifina/service/StreamrClientServiceIntegrationSpec.groovy
test/unit/com/unifina/service/StreamrClientServiceSpec.groovy

Attempt at fixing integration tests.
```
| Failure:  getInstanceForThisEngineNode() uses sessionService to generate a sessionToken (instead of making an API call)(com.unifina.service.StreamrClientServiceIntegrationSpec)
|  Too many invocations for:
1 * service.sessionService.generateToken(_)   (2 invocations)
Matching invocations (ordered by last occurrence):
2 * <SessionService>.generateToken(com.unifina.domain.security.SecUser : 1531)   <-- this triggered the error
at org.spockframework.mock.runtime.MockInteraction.accept(MockInteraction.java:73)
at org.spockframework.mock.runtime.MockInteractionDecorator.accept(MockInteractionDecorator.java:46)
at org.spockframework.mock.runtime.InteractionScope$1.accept(InteractionScope.java:41)
at …
```

Fix integration tests

---

grails-app/controllers/com/unifina/controller/api/StreamApiController.groovy
src/java/com/unifina/api/NotPermittedException.java
test/unit/com/unifina/controller/api/StreamApiControllerSpec.groovy

Fix the error message when user makes a request to the `/streams/{id}` endpoint, but is missing the `stream_get` permission. Reported by @mondoreale [here](https://github.com/streamr-dev/streamr-platform/pull/1013#issuecomment-637405757)

Fix error message

---

grails-app/services/com/unifina/service/DataUnionJoinRequestService.groovy

The current `broker` version still requires `stream_get` (as well as `stream_publish`) to publish messages. 
This will be fixed in the future, but for the time being let's work around this by granting both `stream_get` as well as `stream_publish` to DU joiners.

Grant stream_get on DU join

---

grails-app/conf/Config.groovy

This is to debug an issue noticed in 2020-08-19 where join had stopped working for 0x3650b99D107d581eF8ff004365A4Ada8DA6bf62F (still working for 0x600Ee6e7bB9Cbfe21efd41969ec5F26d00F98155). EE doesn't log anything, but data isn't received by stream listeners anywhere.

Find out in more detail how join request service is doing

---

grails-app/services/com/unifina/service/PermissionService.groovy
grails-app/services/com/unifina/service/ProductService.groovy
test/integration/com/unifina/service/PermissionServiceIntegrationSpec.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy

Sending a PUT to the /products/id endpoint seems to recreate the public Permission rows, if the product is a free product.
This PR fixes the issue, but there is a separate bug BACK-6 which will be fixed in another PR.

CORE-1921: updating recreates permissions

---

grails-app/services/com/unifina/service/DataUnionJoinRequestService.groovy
grails-app/services/com/unifina/service/ProductService.groovy
test/integration/com/unifina/service/DataUnionJoinRequestServiceIntegrationSpec.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy

The backend manages the permissions of DU members, giving them `STREAM_GET` and `STREAM_PUBLISH` permissions when they join. However, when they leave or when Streams are added/removed from the Product, I noticed that only `STREAM_PUBLISH` was updated. This PR adds `STREAM_GET` management also, so that the two always go hand in hand.
@kare @teogeb could you take over and update the tests please?

BACK-20 DU members should have STREAM_GET and STREAM_PUBLISH permissions

---

grails-app/services/com/unifina/service/ProductService.groovy
grails-app/services/com/unifina/service/ProductStore.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy

Fixes a bug where a stream is removed from a product, but it still belongs to another free product. The stream should retain the anonymous access permission.

BACK-6: Anonymous permissions should not be revoked when a stream belongs multiple free products

---

grails-app/domain/com/unifina/domain/Product.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2020-09-15-add-DU-version-field-to-product.groovy
grails-app/services/com/unifina/service/ProductService.groovy
rest-e2e-tests/products-api.test.js
rest-e2e-tests/schemas/product.json
src/groovy/com/unifina/service/CreateProductCommand.groovy

Added new "dataUnionVersion" field to product and updated POST /api/v1/products to read that from input JSON.

BACK-31: Add Data Union version field to Product

---

rest-e2e-tests/canvas-api.stress-test.js
rest-e2e-tests/package.json
rest-e2e-tests/permissions-api.stress-test.js
rest-e2e-tests/permissions-api.test.js

Separate normal end-to-end tests and stress tests so that we can run either of those test suites easily.
There are three NPM scripts:
- ```npm test``` - all tests
- ```npm test:e2e``` - normal end-to-end tests
- ```npm test:stress``` - stress tests

BACK-38: Separate stress tests

---

grails-app/controllers/com/unifina/controller/AuthApiController.groovy

Currently reads from the query parameter, which is incompatible with frontend implementation.

BACK-60: Reset password should read the token from JSON

---

grails-app/migrations/changelog.groovy
grails-app/migrations/core/2020-10-01-remove-anonymous-keys-delete-and-edit-permissions.groovy

Delete all "stream_delete" and "stream_edit" permissions that are attached to anonymous keys.
An earlier migration script `2020-01-24-new-permissions.groovy` created most/all of these permissions when it migrated old "write" permissions to "stream_edit"+"stream_publish"+"stream_delete".

BACK-61: Anonymous keys don't need "stream_delete" and "stream_edit" permissions

---

docs/swagger.json
grails-app/domain/com/unifina/domain/Stream.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2020-10-01-remove-inbox-stream.groovy
grails-app/services/com/unifina/service/EthereumIntegrationKeyService.groovy
grails-app/services/com/unifina/service/StreamService.groovy
rest-e2e-tests/schemas/stream.json
src/groovy/com/unifina/controller/StreamListParams.groovy
test/unit/com/unifina/service/EthereumIntegrationKeyServiceSpec.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy
test/unit/com/unifina/service/StreamServiceSpec.groovy

Remove implementation of inbox stream functionality. Delete inbox streams from DB, permissions of those streams and inbox-column of `stream` table.
The migration scripts deletes ~22k inbox streams and ~132k permissions.

BACK-63: Remove inbox stream functionality

---

grails-app/controllers/com/unifina/controller/LoginApiController.groovy
grails-app/domain/com/unifina/domain/SignupMethod.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2020-09-18-convert-API-keys-to-Ethereum-IDs.groovy
grails-app/services/com/unifina/service/EthereumIntegrationKeyService.groovy
grails-app/services/com/unifina/service/UserService.groovy
src/java/com/unifina/controller/TokenAuthenticator.java
src/java/com/unifina/security/ApiKeyConverter.java
test/unit/com/unifina/controller/LoginApiControllerSpec.groovy
test/unit/com/unifina/controller/LogoutApiControllerSpec.groovy
test/unit/com/unifina/controller/RESTAPIFiltersSpec.groovy
test/unit/com/unifina/controller/UserApiControllerSpec.groovy
test/unit/com/unifina/security/ApiKeyConverterSpec.groovy

All API keys are converted to Ethereum integration keys. 
The database migration script converts API keys to integration keys with a deterministic function, inserts the keys to the DB and deletes the API keys. It creates new anonymous users for keys that don't belong to any user.
API key authentication is still supported: when a user authenticates with an API key, TokenAuthenticator calculates the integration key from the API key and finds the user by that integration key.
After this PR has been merged, we can most likely remove all remaining API key functionality (expect the TokenAuthenticator functionality described above) and drop the `Key` from the DB. Those changes will be done in a separate PR.
Open questions:
- There is an endpoint `/api/v1/login/apikey` where a user can create a …

BACK-12: Convert api keys to Ethereum IDs

---

grails-app/conf/BuildConfig.groovy
grails-app/conf/UrlMappings.groovy
rest-e2e-tests/canvas-api.stress-test.js
rest-e2e-tests/categories-api.test.js
rest-e2e-tests/cors.test.js
rest-e2e-tests/dataunions-api.test.js
rest-e2e-tests/notfound-api.test.js
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json
rest-e2e-tests/permissions-api.stress-test.js
rest-e2e-tests/permissions-api.test.js
rest-e2e-tests/products-api.test.js
rest-e2e-tests/storagenode-api.test.js
rest-e2e-tests/streamr-api-clients.js
rest-e2e-tests/streams-api.test.js
rest-e2e-tests/subscriptions-api.test.js

- Configure the Grails embedded tomcat plugin to allow encoded slash in URI when using `grails run-app` and `grails run-war`.
- To verify that the change works, added e2e test for `GET`ting streams with slashes and dots in the stream id
- Some e2e tests communicated with the API via nginx, some directly to port 8081. Updated all e2e tests to use the nginx routing to really make them end-to-end.

Configure tomcat to allow encoded slash in uri

---

rest-e2e-tests/streamr-api-clients.js

End-to-end tests should encode URL parameters to support e.g. custom stream IDs.

BACK-75: End-to-end tests: encode URL path parameters

---

grails-app/controllers/com/unifina/controller/PermissionApiController.groovy
grails-app/domain/com/unifina/domain/Permission.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2020-10-23-remove-API-key-permission.groovy
grails-app/services/com/unifina/service/PermissionService.groovy
src/groovy/com/unifina/domain/Resource.groovy
test/integration/com/unifina/service/PermissionServiceDeleteIntegrationSpec.groovy
test/integration/com/unifina/service/PermissionServiceIntegrationSpec.groovy
test/unit/com/unifina/controller/PermissionApiControllerSpec.groovy
test/unit/com/unifina/controller/StreamApiControllerSpec.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy

API keys are deprecated and all keys have been migrated to Ethereum integration keys. There are no permissions that belong to keys anymore.
Remove the functionality that handles key permissions and remove "key_id" column from permission table.

BACK-79: Remove API-key permission handling

---

docs/swagger.json
grails-app/services/com/unifina/service/StreamService.groovy
rest-e2e-tests/streams-api.test.js

Should be able to set autoConfigure, storageDays and inactivityThresholdHours when creating a stream by POST /api/v1/streams

Bug: storageDays ignored by back-end on POST /api/v1/streams

---

rest-e2e-tests/canvas-api.stress-test.js
rest-e2e-tests/categories-api.test.js
rest-e2e-tests/cors.test.js
rest-e2e-tests/dataunions-api.test.js
rest-e2e-tests/login-api.test.js
rest-e2e-tests/notfound-api.test.js
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json
rest-e2e-tests/permissions-api.stress-test.js
rest-e2e-tests/permissions-api.test.js
rest-e2e-tests/products-api.test.js
rest-e2e-tests/schema-validator.js
rest-e2e-tests/storagenode-api.test.js
rest-e2e-tests/streamr-api-clients.js
rest-e2e-tests/streams-api.test.js
rest-e2e-tests/subscriptions-api.test.js
rest-e2e-tests/test-utilities.js

Converted most of the endpoints to use private key authentication. API authentication is used only in login endpoints (for testing API key related functionality). 
The tests create new users when possible so that there is no dependency to the DB state. 
Also converted the tests to use the official JS client where it supports the required endpoint.
Most of the tests users in the DB could be removed if not used outside of E&E. The only user that the tests need is "devOpsUser" (id=6).

BACK-77: Convert e2e-tests to use private key authentication

---

docs/swagger.json
grails-app/controllers/com/unifina/controller/StorageNodeApiController.groovy
grails-app/services/com/unifina/service/StorageNodeService.groovy
rest-e2e-tests/storagenode-api.test.js
rest-e2e-tests/test-utilities.js
src/groovy/com/unifina/domain/EthereumAddress.groovy
src/java/com/unifina/service/ValidationException.java
test/unit/com/unifina/domain/EthereumAddressSpec.groovy

Support case-insensitive input of storage node address. Store the address to DB in Ethereum checksum form and output the JSONs in that form.
EthereumAddress object is parsed from the command JSON manually and StreamStorageNode's field type is just a plain string instead of an EthereumAddress instance. If it is possible, string<->EthereumAddress conversions should happen automatically. We can enhance the functionality in BACK-85 if we apply this logic to the whole application.
Another small functionality change: if the request path has a malformed Ethereum address, the endpoint returns HTTP 422 (previously  HTTP 400).

BACK-7: Storage node case sensitivity

---

.travis_scripts/streamr-client-test.sh

- Run `stream-cleartext-signed` client tests instead of `stream-encrypted-shared-rotating-signed`
- Other client test options fail locally
- Expecting step to be green from now on
- Step is still allowed to fail

BACK-86: Fix streamr-client-testing

---

grails-app/controllers/com/unifina/controller/StreamApiController.groovy
rest-e2e-tests/streams-api.test.js
test/unit/com/unifina/domain/CustomStreamIDValidatorSpec.groovy

Allow users to create streams with the naming pattern `<address>/<path>` where `<address>` is an Ethereum address connected to the user.

BACK-94: Create streams under own address

---

docs/swagger.json
rest-e2e-tests/streams-api.test.js
src/groovy/com/unifina/domain/CustomStreamIDValidator.groovy
test/unit/com/unifina/domain/CustomStreamIDValidatorSpec.groovy
test/unit/com/unifina/service/StreamServiceSpec.groovy
test/unit/com/unifina/signalpath/streams/CreateStreamSpec.groovy
test/unit/com/unifina/signalpath/streams/GetOrCreateStreamSpec.groovy

Remove the hard-coded shared `sandbox` domain, as it is now redundant after BACK-94.

BACK-97: Drop support for "sandbox" domain

---

grails-app/conf/BuildConfig.groovy
grails-app/conf/DataSource.groovy
grails-app/conf/spring/resources.groovy

c3p0 connection pool has had reliable track record over the years and is considered industry "standard" over Tomcat connection pool.
- Current Mysql driver is JDBC 4(.2) compatible. Don't set preferredTestQuery.
- c3p0 fixes an issue where JDBC connections were closed prematurely:
```
java.sql.SQLException: PooledConnection has already been closed.
at com.unifina.service.SessionService$$ESH9pQjI.generateToken(SessionService.groovy:26)
at com.unifina.controller.LoginApiController.apikey(LoginApiController.groovy:55)
at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:100)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

BACK-71: Replace Tomcat connection pool with c3p0

---

rest-e2e-tests/login-api.test.js

Login REST API test POST /api/v1/login/apikey has started to timeout after BACK-12. Lets increase the timeout temporarily until BACK-92 is done.

BACK-108: Increase REST API Login test timeout

---

.travis_scripts/rest_e2e_test.sh

Start only required Docker containers.
CI build time dropped from ~15min to ~13min.

DEVOP-20: Optimise E&E CI: REST E2E tests

---

grails-app/conf/BuildConfig.groovy

- Only S3 is used by E&E
- Cuts down build time a few seconds

BACK-107: Replace full AWS jar with ASW S3 jar

---

.dockerignore
.travis.yml
.travis_scripts/integration_test.sh
.travis_scripts/rest_e2e_test.sh
.travis_scripts/smoke_test.sh
.travis_scripts/streamr-client-test.sh

- Run common commands for all steps in the `before_install:` step
- Removes a lot of duplication
- By default all steps get the following setup out-of-the-box:
- Default Mysql provided by Travis CI is in stopped state
- Grails 2.5.6 installed
- `streamr-docker-dev` installed in `$PATH`
- `streamr-docker-dev` networking
- If built, use local Docker image for E&E `streamr-docker-dev/engine-and-editor:local`
- Installs Node defined in `rest-e2e-tests/.nvmrc` for running REST API tests

BACK-110: Reorganise Travis CI build

---

grails-app/conf/Config.groovy

Simplify configuration initialisation for `streamr.ethereum.nodePrivateKey` key in `Config`

Simplify configuration initialisation for streamr.ethereum.nodePrivateKey

---

.github/workflows/markdown-link-check.yaml

- Scheduled to run on Monday mornings (Helsinki time)

DEVOP-51: Validate Markdown links in GitHub Actions

---

src/java/com/unifina/signalpath/blockchain/Web3jHelper.java

Fetch the owner of an ENS domain directly from the registry contract.  There is no need to fetch the resolver of the ENS domain and read the attributes from the resolver.
In production environment we use 
`function owner(bytes32 node) external view returns (address)`
from
https://etherscan.io/address/0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e#code
In dev we use the same function from contract `0x92E8435EB56fD01BF4C79B66d47AC1A94338BB03`
The earlier implementation did not read the owner information correctly. It fetched the owner information from resolver's `addr` function: https://etherscan.io/address/0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41#code  (that field contains the same information in some cases, e.g. https://app.ens.domains/name/purplemonkeydishwasher.eth)

BACK-126: Read ENS owner from registry contract

---

docs/swagger.json
grails-app/domain/com/unifina/domain/Product.groovy
rest-e2e-tests/schemas/product.json

In the "summary" rendering of `Product` (as output by the list endpoint), there was a `streams` array which was hard-coded to an empty array for whatever old reason.
These are just quick, minimal changes to clean it up. If someone wants to take over and improve the docs, feel free to add to this PR. I just removed it as a required field from the swagger spec.
Cc @juhah, risk of frontend starting to fail validation of `Product` objects due to the missing `streams` field.

BACK-129: remove empty streams array from Product list

---

grails-app/domain/com/unifina/domain/SignupMethod.groovy
grails-app/services/com/unifina/service/BalanceService.groovy
grails-app/services/com/unifina/service/BootService.groovy
grails-app/services/com/unifina/service/DataUnionJoinRequestService.groovy
grails-app/services/com/unifina/service/KeyValueStoreService.groovy
grails-app/services/com/unifina/service/StorageNodeService.groovy
grails-app/services/com/unifina/service/StreamrClientService.groovy
src/groovy/com/unifina/domain/EthereumAddress.groovy
src/java/com/unifina/signalpath/blockchain/EthereumModuleOptions.java
src/java/com/unifina/signalpath/blockchain/Web3jHelper.java
src/java/com/unifina/utils/ApplicationConfig.groovy
test/integration/com/unifina/service/KeyValueStoreServiceIntegrationSpec.groovy
test/unit/com/unifina/domain/EthereumAddressSpec.groovy

Sends an event to a separate event stream when a streams is added to a storage node (or removed from a storage node).
All events are sent to the same stream (${EE_address}/storage-node-assignments`), and the stream is created when the application starts, if needed.

NET-187: Event stream for storage node assignments

---

docs/swagger.json
rest-e2e-tests/canvas-api.stress-test.ts
rest-e2e-tests/categories-api.test.ts
rest-e2e-tests/dataunions-api.test.ts
rest-e2e-tests/notfound-api.test.ts
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json
rest-e2e-tests/permissions-api.stress-test.ts
rest-e2e-tests/permissions-api.test.ts
rest-e2e-tests/products-api.test.ts
rest-e2e-tests/storagenode-api.test.ts
rest-e2e-tests/streamr-api-clients.ts
rest-e2e-tests/streams-api.test.ts
rest-e2e-tests/subscriptions-api.test.ts
rest-e2e-tests/test-utilities.ts

Updated test to be compatible with JS-client v5.x
Small fix to swagger documentation about permission.id

Update end-to-end tests to use JS-client v5.x

---

.github/workflows/ci-cd.yaml

Use specific version of Ubuntu. Tag `ubuntu-latest` just got updated to `ubuntu-20.04` which causes unit test JVM to crash.

BACK-139: Use Ubuntu 18.04 on GitHub Actions CI and CD build

---

grails-app/domain/com/unifina/domain/Stream.groovy
grails-app/services/com/unifina/service/StorageNodeService.groovy
src/java/com/unifina/service/NotifyStorageNodeTask.java

When stream is added to storage node or removed from it, the E&E notifies the broker by publishing event to `0xFCAd0B19bB29D4674531d6f115237E16AfCE377c/storage-node-assignments` stream. Changed that publish task to be asynchronous background operation. 
The add/remove operation doesn't need to wait for the notification task to complete. E&E can respond with a success status even if the notification fails from some reason.

NET-187: Notify storage node assignment in background

---

rest-e2e-tests/canvas-api.stress-test.ts
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json

Update tests to be compatible with manual storage node configuration (https://github.com/streamr-dev/broker/pull/211) by explicitly adding a stream to the storage node if it needs historical data.

NET-193: Manual storage config in tests

---

grails-app/services/com/unifina/service/StorageNodeService.groovy
rest-e2e-tests/src/storagenode-api.test.ts

When a client tries to assign storage node again (POST /streams/{id}/storageNodes) to the same storage node replies with 200 instead of 400.

fix(api/storage): Fixes BACK-155

---

docs/swagger.json
grails-app/services/com/unifina/service/StreamService.groovy
rest-e2e-tests/src/products-api.test.ts
rest-e2e-tests/src/streams-api.test.ts
rest-e2e-tests/src/test-utilities.ts
src/java/com/unifina/service/ValidationException.java

The `ValidationException` message now includes the rejected value. The content is shorter and easier to interpret, e.g.:
```
Invalid id: 0x1234567890/foobar
Invalid partitions: 999 (max.exceeded)
Invalid category: non-existing-category-id (typeMismatch)
```

Improve validation error messages

---

grails-app/services/com/unifina/service/PermissionStore.groovy
test/unit/com/unifina/service/PermissionServiceSpec.groovy

Problem:
* MySQL cpu usage at 770%
* `show full processlist;` showing 102 processes from streamr-prod-2 in queue at all times
* those queries VERY slow (50 seconds)
Quick testing:
* get only user-specific permission: 0.2s
* get only anonymous permission (when there are none): 5s
* get user-specific OR anonymous permission: 50s
Solution: only ask MySQL for anonymous permissions if no user-specific permissions found.
Reason could be a bad index: in `TABLE permission`, there is `KEY `anonymous_idx` (`anonymous`)` but that column only has 2 possible values. So maybe not so good to index it.

fix: slow permission query killing core-api

---

src/java/com/unifina/service/NotifyStorageNodeTask.java

The message to notify storage nodes about new storage assignments did not contain what storage node the stream was assigned to!

add storage node address to notification message

---

grails-app/services/com/unifina/service/StorageNodeService.groovy

Optimized `/api/v1/storageNodes/:streamId/streams` endpoint. 
Previously we fetched the list of `streamIds` and the fetched each stream one by one  The new implementation uses single query to fetch all required data.
Previously the endpoint query took about 14 seconds if there is 10000 streams in a storage node (in local environment). After the optimization the same operation takes about 1 second.

optimize findStreamsByStorageNode

---

src/groovy/com/unifina/domain/EthereumAddress.groovy
src/java/com/unifina/service/NotifyStorageNodeTask.java

This seems to be serialized as `{storageNode: {value: string}}` instead of just `{storageNode: string}`, which breaks the broker.

Fix bad serialization of storageNodeAddress.

---

.dockerignore
grails-app/controllers/com/unifina/controller/StreamApiController.groovy
test/unit/com/unifina/controller/StreamApiControllerSpec.groovy

When Stream is updated (HTTP PUT) with `migrateToBrubeck = true` set `migrateToBrubeck` to `true` and set `migrateSyncTurnedOnAt` to current time.

BACK-202: update migration fields
