test/functional/GebConfig.groovy

Run functional tests from IntelliJ

Fix CORE-1206

---

.travis.yml
travis-after-failure.sh

First steps in TravisCI integration (less is more).
* Add Integration tests
* Add Unit tests
* Build WAR
* Deploy WAR to S3 Bucket
Closes: None

chore: CORE-1213 - TravisCI integration vs Jenkins:

---

web-app/js/unifina/streamr-chart/streamr-chart.js

Sorry about the changes on trailing spaces (IDE). The real change is on line 331

[CORE-1216] Remove console logging from streamr-chart.js

---

.travis.yml
README.md

* Add Slack Notification Secret
* Update the README to include the build badge
Related: CORE-1213

feat: CORE-1219 - TravisCI support for Slack:

---

.travis.yml

* Change upload directory from editor-engine to engine-editor

fix: CORE-1222 - Travis pushing release war to S3 with wrong key:

---

web-app/react-app/components/ProfilePage/IdentityHandler/index.jsx
web-app/react-app/components/ProfilePage/IntegrationKeyHandler/index.jsx
web-app/react-app/tests/components/ProfilePage/IdentityHandler/identityHandler.test.js
web-app/react-app/tests/components/ProfilePage/IntegrationKeyHandler/integrationKeyHandler.test.js
web-app/react-app/tests/utils/web3Provider.test.js
web-app/react-app/utils/web3Provider.js

Reverts streamr-dev/engine-and-editor#397
tests failing after all... ouch.

Revert "Core 1193 show eth data balance"

---

Dockerfile
Dockerfile.optimized

chore: CORE-1264 : Update to java8

---

grails-app/migrations/changelog.groovy
grails-app/migrations/core/2018-04-04-test-data-products-subscriptions.groovy

based it on thumbnail branch because then it's "ready to roll out" with thumbnail_url included.

Core 1259 mock product data

---

Dockerfile

fix: CORE-1264 Fix docker build

---

grails-app/conf/UrlMappings.groovy
package.json
rest-e2e-tests/products-api.js
rest-e2e-tests/schema-validator.js
rest-e2e-tests/schemas/permission.json
rest-e2e-tests/streamr-api-clients.js

Fetch my permissions to a Product.
Used by front-end to check whether user can edit Product or not.

CORE-1221: GET /api/v1/products/:id/permissions/me

---

grails-app/services/com/unifina/service/StreamService.groovy

* CompileStatic on change is causing SEGENV on functional tests

fix: CORE-1081 - java8-compatability:

---

grails-app/conf/UrlMappings.groovy
web-app/misc/swagger.json

API endpoint `user/me/products`

CORE-1287: API endpoint for listing my products

---

grails-app/views/canvas/editor.gsp
web-app/js/unifina/signalPath/controls/canvas-start-button.js
web-app/js/unifina/signalPath/core/Parameter.js
web-app/js/unifina/streamr-search/streamr-search.js
web-app/js/unifina/streamr.js

Mainly please review the first commit (b827).
Additional suggestions for escapings are welcome, though maybe better merge this thing first.

Core 1297 javascript injections

---

.travis.yml
package.json

* Fixed version for eslint-config-streamr

fix: CORE-1349 - Webpack does not build for development environment

---

grails-app/services/com/unifina/service/ProductService.groovy
rest-e2e-tests/products-api.test.js
src/groovy/com/unifina/api/UpdateProductCommand.groovy
test/unit/com/unifina/api/UpdateProductCommandSpec.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy
web-app/misc/swagger.json

Allows updating price, owner, beneficiary, and other Blockchain-related information of a Product when it is in State = `NOT_DEPLOYED` and it is free `price = 0`.

CORE-1347: allow updating Blockchain info of undeployed Product

---

grails-app/conf/Config.groovy

* Allow mail enviroment variable to be configurable

feat: Configurable mail parameters:

---

grails-app/migrations/changelog.groovy
grails-app/migrations/core/2018-04-27-insert-categories.groovy

Add initial product categories

CORE-1359: add initial product categories

---

grails-app/i18n/messages.properties
grails-app/views/layouts/_topnav.gsp

Enable users to return to marketplace from e&e.

Add link to marketplace.streamr.com

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/CanvasSizesApiController.groovy
grails-app/services/com/unifina/service/SignalPathService.groovy

Quick admin-only API for listing canvases and their sizes. Will write proper tests / clean up later.

CORE-1452: quick API for canvas sizes

---

.travis.yml

* Upload war to staging account

chore: CORE-1234 - Deploy engine editor stg:

---

.appspec.yml
.travis.yml
travis_scripts/build_war.sh

* Convert release to codedeploy bundle
* Insert codedpeloy provider

chore: Add codedeploy support:

---

Dockerfile

* Version 2.28 doesn't work on the EE
* Fix location of pub key

fix: CORE-1509 - Downgrade glibc:

---

grails-app/services/com/unifina/service/SignalPathService.groovy
test/unit/com/unifina/service/SignalPathServiceSpec.groovy

CORE-1468: allow admin to stop canvas

---

.codedeploy/.appspec.yml
.codedeploy/after_install.sh
.codedeploy/before_install.sh
.codedeploy/start_server.sh
.codedeploy/stop_server.sh
travis_scripts/build_war.sh

* Move all codedeploy files to their own dir
* Fetch executables from codedeploy file and not AWS

fix: Fix codedeploy errors:

---

grails-app/conf/Config.groovy

Allows user to login and logout via new frontend.

Enable CORS for /login/* and /logout/* endpoints

---

src/java/com/unifina/signalpath/utils/Filter.java
src/java/com/unifina/signalpath/utils/PassThrough.java
test/unit/com/unifina/signalpath/utils/FilterSpec.groovy
test/unit/com/unifina/signalpath/utils/PassThroughSpec.groovy

Previously classes were removed since they were marked as deprecated, but actually are not.

Add Filter and PassThrough classes

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/MetricsApiController.groovy
grails-app/services/com/unifina/service/MetricsService.groovy
src/java/com/unifina/data/EventQueueMetrics.java
src/java/com/unifina/data/HistoricalEventQueue.java
src/java/com/unifina/data/HistoricalEventQueueMetrics.java
src/java/com/unifina/data/RealTimeEventQueueMetrics.java
src/java/com/unifina/data/RealtimeEventQueue.java
src/java/com/unifina/datasource/DataSource.java
src/java/com/unifina/datasource/DataSourceEventQueue.java

Todo:
- serialization of canvases and calculate sizes
Questions:
- Any other metrics we want to gather? I think the JVM-level and server-level metrics can be gathered with other tools.

CORE-1510: application-level metrics

---

.travis.yml

fix: DEVOPS-6 - Fix encryption:

---

grails-app/conf/ApplicationResources.groovy

Created a new issue, branch and PR since I wasn't sure what changes needed to be done in order this to work (it has never been used). It worked out-of-the-box so this PR ended up to be only 1 line:)

[CORE-1557] Y-axis selector button not visible in chart

---

src/java/com/unifina/signalpath/blockchain/GetEthereumContractAt.java

weirdest thing that this feature has not been merged to master

ABI lookup in Etherscan

---

src/java/com/unifina/signalpath/blockchain/EthereumJsonRpc.java

Content-Type header added to JSON RPC call

---

grails-app/conf/Config.groovy

* Add /j_spring_security_logout

feat: CORE-1567- Enable cors for marketplace

---

src/java/com/unifina/signalpath/blockchain/ContractEventPoller.java

Error message is [Unable to uninstall filter null]

fix race condition causing error message

---

.idea/dataSources.local.xml
grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/NodeApiController.groovy
test/unit/com/unifina/controller/api/NodeApiControllerSpec.groovy

Helps debug problems in staging/production

Add admin endpoint that returns current Grails config

---

.travis.yml

* Remove building prod war and docker image in PR phase

chore: DEVOPS-22 - Make EE PR travisCI faster:

---

test/unit/com/unifina/security/UserJavaClassLoaderSpec.groovy

I think it's good to test for the specific feature even though the "is securitymanager installed" covers it for now

Re-add a test from an unmerged branch

---

.codedeploy/before_install.sh

* Remove folder to guarantee everything is updated

fix: Remove artifact folder:

---

.travis.yml

fix: Update code deploy naming:

---

grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/ModuleApiController.groovy
grails-app/controllers/com/unifina/controller/signalpath/ModuleController.groovy
web-app/misc/swagger.json

Copy methods of `/module/jsonGetModule` and `/module/jsonGetModuleTree` into `ModuleApiController` and create new URL mappings `/api/v1/modules/jsonGetModule` and `/api/v1/modules/jsonGetModuleTree`.
Tested by hand that works.

CORE-1642: move /module/jsonGetModule and /module/jsonGetModuleTree under API

---

grails-app/conf/UrlMappings.groovy

Current mappings are:
- GET "/api/v1/users/me"
- PUT "/api/v1/users/me/update"
- DELETE "/api/v1/users/me/delete"

CORE-1650: Fix URL mappings for user delete/update/info

---

src/java/com/unifina/feed/FieldDetector.java
src/java/com/unifina/feed/map/MapMessageEventRecipient.java
test/unit/com/unifina/feed/FieldDetectorSpec.groovy

I got this problem when trying to run engine-and-editor. Curiously I only got it after very thorough cleanup, some it could be just compilers acting funny.
For me it seems though that getContent throws IOException which is checked exception. Has this worked for you without catching it?

fix: Java client API change

---

grails-app/services/com/unifina/service/SessionService.groovy
test/unit/com/unifina/service/SessionServiceSpec.groovy

Noticed this issue and threw together a quick fix.

Ignore StaleObjectStateException when updating lastLogin

---

src/java/com/unifina/feed/cassandra/CassandraDataRangeProvider.java
src/java/com/unifina/feed/cassandra/CassandraDeletingStreamListener.java

Updated some forgotten classes to work with the new Cassandra tables. Didn't bother adding tests as these classes will be thrown out soon enough anyway.
EDIT: tested by hand.

Fix cassandra queries

---

.travis.yml
travis_scripts/build_war.sh

* add Travis job id to name of deployment tar
* Remove Lisbon Deployment (cleanup)

chore: DEVOPS-85 Add versioning to staging:

---

src/java/com/unifina/signalpath/blockchain/GetEvents.java
src/java/com/unifina/signalpath/blockchain/SendEthereumTransaction.java
src/java/com/unifina/signalpath/blockchain/SolidityCompileDeploy.java
src/java/com/unifina/signalpath/blockchain/Web3jHelper.java
test/unit/com/unifina/signalpath/blockchain/SendEthereumTransactionSpec.groovy
test/unit/com/unifina/signalpath/blockchain/Web3jHelperSpec.groovy

- uses PENDING block to compute nonce. fixes the multiple transaction issue
- I added a small fix to Web3jHelper that allows "address" type to be instantiated from BigInteger and Uint160 in addition to String. This was in my PR to web3j, but didn't make it into web3j PR to E&E

CORE-1719 use PENDING block to compute nonce, GetEvents bugfix

---

grails-app/controllers/com/unifina/controller/api/UserApiController.groovy
test/unit/com/unifina/controller/api/UserApiControllerSpec.groovy

This is part of the same fix as this PR: https://github.com/streamr-dev/streamr-client-javascript/pull/68

getUserInfo return key info when authenticating with anon key

---

Dockerfile.dev

* To improve docker linking it is necessary curl for healthchecks

fix: Add Curl:

---

src/java/com/unifina/signalpath/blockchain/EthereumModuleOptions.java
src/java/com/unifina/signalpath/blockchain/SendEthereumTransaction.java

configurable gas limit for EthereumCall

added gasLimit input to SendEthereumTransaction

---

.idea/dataSources.local.xml
grails-app/conf/UrlMappings.groovy
grails-app/controllers/com/unifina/controller/api/CommunityJoinRequestApiController.groovy
grails-app/controllers/com/unifina/controller/api/CommunitySecretApiController.groovy
grails-app/services/com/unifina/service/CommunityOperatorService.groovy
grails-app/services/com/unifina/service/EthereumService.groovy
src/java/com/unifina/signalpath/blockchain/Web3jHelper.java
test/unit/com/unifina/controller/api/CommunityJoinRequestApiControllerSpec.groovy
test/unit/com/unifina/controller/api/CommunitySecretApiControllerSpec.groovy

Hotfix community fixes

---

.travis.yml

chore: Build war for lisbon enviroment:

---

.travis.yml

fix: Dont deploy lx enviroment in stg:

---

docker/Dockerfile.dev

fix: DEVOPS-161 - test db:

---

src/java/com/unifina/signalpath/blockchain/ContractEventPoller.java
src/java/com/unifina/signalpath/blockchain/EthereumJsonRpc.java
src/java/com/unifina/signalpath/blockchain/GetEvents.java
src/java/com/unifina/signalpath/blockchain/HttpEthereumJsonRpc.java
src/java/com/unifina/signalpath/blockchain/JsonRpcResponseHandler.java
src/java/com/unifina/signalpath/blockchain/SendEthereumTransaction.java
src/java/com/unifina/signalpath/blockchain/Web3jHelper.java
src/java/com/unifina/signalpath/blockchain/WebsocketEthereumJsonRpc.java

- WS connector applies filter on reconnect and "no filter" error
- RPC errors checked, logged, no exception thrown
- check for null timestamp within non-null block

fix WS reconnection err

---

.idea/dataSources.local.xml
docs/swagger.json
grails-app/controllers/com/unifina/controller/api/ProductApiController.groovy
grails-app/domain/com/unifina/domain/data/Stream.groovy
grails-app/domain/com/unifina/domain/marketplace/Product.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2019-09-27-alter-pending-changes.groovy
rest-e2e-tests/schemas/product.json
src/groovy/com/unifina/api/UpdateProductCommand.groovy
test/unit/com/unifina/api/UpdateProductCommandSpec.groovy
test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
test/unit/com/unifina/domain/marketplace/ProductSpec.groovy

- Support PUT
- Change sql datatype to TEXT

CORE-1797: Fix JSON encoding/deconding

---

src/java/com/unifina/data/ClockTick.java
src/java/com/unifina/data/Event.java

Event age 99203: Thu Oct 31 12:11:49 UTC 2019 - content: com.unifina.data.ClockTick@4d91d1e9
->
Event age 90639: Event[timestamp=Thu Oct 31 14:04:22 UTC 2019,content=ClockTick[timestamp=1572530662003]]

Improve log message

---

.travis.yml
Makefile
rest-e2e-tests/canvas-api.test.js
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json

Update REST API test dependencies

---

Dockerfile

* Refelect env changes to CATALINA_OPTS

fix: DEVOPS-181 AWS Image upload for docker:

---

grails-app/controllers/com/unifina/controller/api/PermissionApiController.groovy
grails-app/services/com/unifina/service/PermissionService.groovy

this happens when creating community in dev environment
probably should also create the "node address" user on startup

Fix NPE when granting WRITE or SHARE to non-existing Ethereum address

---

test/unit/com/unifina/utils/BoundedPriorityBlockingQueueSpec.groovy

Testing if this change removes unit test flakiness on CI. Locally both old and new version passed when run multiple times.

try fixing unit test flakiness

---

.travis_scripts/integration_test.sh
.travis_scripts/rest_e2e_test.sh
.travis_scripts/smoke_test.sh

- ✅ Validate that tests pass using `cleanup` branch of `streamr-docker-dev`
- ✅ Switch scripts back to `master` branch (tests will not pass)
- ✅ Wait for streamr-dev/streamr-docker-dev#58 to merge

Update Travis CI scripts for new streamr-docker-dev

---

docs/swagger.json
grails-app/domain/com/unifina/domain/marketplace/Subscription.groovy
rest-e2e-tests/schemas/subscription.json

Trivial change to support [PLATFORM-1238](https://streamr.atlassian.net/browse/PLATFORM-1238).

Expose dateCreated and lastUpdated on Subscription

---

grails-app/conf/BuildConfig.groovy

CORE-1902: Update Grails plugin cors 1.3.0

---

grails-app/conf/BuildConfig.groovy

CORE-1900: Update Grails plugin mail 1.0.8-SNAPSHOT

---

grails-app/conf/BuildConfig.groovy

CORE-1899: Update Grails plugin database-migration 1.4.0 to 1.4.2-SNAPSHOT

---

grails-app/conf/BuildConfig.groovy

CORE-1891: Update Grails Tomcat plugin from 7.0.70 to 8.0.50

---

.travis.yml

* Import aws staging secrets
* Import aws production secrets
* Import docker secrets
* Remove old docker secrets

Import secrets from single location

---

.travis.yml
.travis_scripts/validate_swagger.sh
rest-e2e-tests/canvas-api.test.js
rest-e2e-tests/products-api.test.js

Tests pass locally so trying to just increase timeouts if that would be the issue.

try to fix rest-e2e tests by increasing timeouts

---

.idea/engine-and-editor-grailsPlugins.iml
.idea/engine-and-editor.iml
grails-app/conf/BuildConfig.groovy
grails-app/services/com/unifina/service/CassandraService.groovy
src/groovy/com/unifina/utils/TestUtils.groovy
src/java/com/unifina/feed/FieldDetector.java
src/java/com/unifina/feed/StreamPropagationRoot.java
src/java/com/unifina/signalpath/utils/MessageChainUtil.java
src/java/com/unifina/utils/testutils/FakeStreamrClient.java
test/unit/com/unifina/controller/api/ProductApiControllerSpec.groovy
test/unit/com/unifina/feed/FieldDetectorSpec.groovy
test/unit/com/unifina/service/ProductServiceSpec.groovy
test/unit/com/unifina/service/StreamServiceSpec.groovy
test/unit/com/unifina/signalpath/utils/MessageChainUtilSpec.groovy

Major version bump comes with some interface changes. No new features in this PR, just updating the client and fixing the resulting compile errors.

Update StreamrClient to version 2.0.0

---

grails-app/conf/com/unifina/controller/RESTAPIFilters.groovy
grails-app/controllers/com/unifina/controller/ProductApiController.groovy
src/java/com/unifina/security/StreamrApi.java
test/unit/com/unifina/controller/ClusterApiControllerSpec.groovy
test/unit/com/unifina/controller/DataUnionJoinRequestApiControllerSpec.groovy
test/unit/com/unifina/controller/DataUnionOperatorApiControllerSpec.groovy
test/unit/com/unifina/controller/DataUnionSecretApiControllerSpec.groovy
test/unit/com/unifina/controller/ProductApiControllerSpec.groovy
test/unit/com/unifina/controller/ProductStreamsApiControllerSpec.groovy
test/unit/com/unifina/controller/RESTAPIFiltersSpec.groovy
test/unit/com/unifina/controller/StreamApiControllerSpec.groovy
test/unit/com/unifina/controller/SubscriptionApiControllerSpec.groovy
test/unit/com/unifina/controller/UserApiControllerSpec.groovy

And move to controllers package

BACK-26: Rename UnifinaCoreAPIFilters -> RESTAPIFilters

---

grails-app/controllers/com/unifina/controller/LoginApiController.groovy
grails-app/controllers/com/unifina/controller/NodeApiController.groovy
grails-app/services/com/unifina/service/ApiService.groovy
grails-app/services/com/unifina/service/ChallengeService.groovy
src/groovy/com/unifina/controller/CanvasListParams.groovy
src/groovy/com/unifina/controller/StreamListParams.groovy
src/groovy/com/unifina/service/Challenge.groovy
src/groovy/com/unifina/service/ListParams.groovy
src/java/com/unifina/service/SessionToken.java
test/unit/com/unifina/controller/CanvasApiControllerSpec.groovy
test/unit/com/unifina/controller/CategoryApiControllerSpec.groovy
test/unit/com/unifina/controller/ControllerSpecification.groovy
test/unit/com/unifina/controller/DashboardApiControllerSpec.groovy
test/unit/com/unifina/controller/DashboardItemApiControllerSpec.groovy
test/unit/com/unifina/controller/IntegrationKeyApiControllerSpec.groovy
test/unit/com/unifina/controller/KeyApiControllerSpec.groovy
test/unit/com/unifina/controller/LoginApiControllerSpec.groovy
test/unit/com/unifina/controller/LogoutApiControllerSpec.groovy
test/unit/com/unifina/controller/MockAPIFilters.groovy
test/unit/com/unifina/controller/ModuleApiControllerSpec.groovy
test/unit/com/unifina/controller/PermissionApiControllerSpec.groovy
test/unit/com/unifina/controller/RelatedProductsControllerSpec.groovy
test/unit/com/unifina/controller/RemoveUsersProductsControllerSpec.groovy
test/unit/com/unifina/controller/StreamApiControllerSpec.groovy
test/unit/com/unifina/controller/UserApiControllerSpec.groovy
test/unit/com/unifina/service/ChallengeServiceSpec.groovy
test/unit/com/unifina/service/ChallengeSpec.groovy
test/unit/com/unifina/service/EthereumIntegrationKeyServiceSpec.groovy

Fix cast errors and apply old patches

BACK-62: Fix warnings

---

.idea/engine-and-editor-grailsPlugins.iml
.idea/engine-and-editor.iml
grails-app/conf/BuildConfig.groovy
grails-app/conf/DataSource.groovy
grails-app/services/com/unifina/service/UserService.groovy
src/java/com/unifina/signalpath/ModuleWithUI.java
src/java/com/unifina/utils/HexIdGenerator.java
src/java/com/unifina/utils/IdGenerator.java
test/unit/com/unifina/UiChannelMockingSpecification.groovy
test/unit/com/unifina/service/CanvasServiceSpec.groovy
test/unit/com/unifina/signalpath/ModuleWithUISpec.groovy

This reverts commit f26c16bca6d2ea46c53ea617757885dd405778dc.

Revert "CORE-1893: update Grails hibernate4 plugin 4.3.10 (#755)"

---

grails-app/conf/Config.groovy
grails-app/controllers/com/unifina/controller/StreamApiController.groovy
grails-app/services/com/unifina/service/EnsService.groovy
grails-app/services/com/unifina/service/StreamService.groovy
rest-e2e-tests/notfound-api.test.js
rest-e2e-tests/streams-api.test.js
rest-e2e-tests/test-utilities.js
scripts/entrypoint.sh
src/groovy/com/unifina/domain/CustomStreamIDValidator.groovy
src/java/com/unifina/signalpath/ModuleWithUI.java
src/java/com/unifina/signalpath/streams/CreateStream.java
test/unit/com/unifina/controller/StreamApiControllerSpec.groovy
test/unit/com/unifina/domain/CustomStreamIDValidatorSpec.groovy
test/unit/com/unifina/service/StreamServiceSpec.groovy
test/unit/com/unifina/signalpath/ModuleWithUISpec.groovy
test/unit/com/unifina/signalpath/streams/CreateStreamSpec.groovy
test/unit/com/unifina/signalpath/streams/GetOrCreateStreamSpec.groovy

Allow users to specify stream id if they own the ENS domain name.
The staging environment needs a new environment variable:
ETHEREUM_ENS_REGISTRY_CONTRACT_ADDRESS, value = "0x9Ac9ef900B7E43058169b2AaD8BF6ce31f3703Da"

BACK-14: ENS stream id

---

src/groovy/com/unifina/controller/ChallengeResponseCommand.groovy
src/groovy/com/unifina/controller/SaveIntegrationKeyCommand.groovy
test/unit/com/unifina/controller/LoginApiControllerSpec.groovy

While at it, remove useless blank definitions.

BACK-83: Add validation for address fields

---

grails-app/conf/BuildConfig.groovy
grails-app/services/com/unifina/service/DataUnionJoinRequestService.groovy
grails-app/services/com/unifina/service/ProductService.groovy
rest-e2e-tests/dataunions-api.test.js
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json
rest-e2e-tests/streamr-api-clients.js
rest-e2e-tests/test-utilities.js
test/integration/com/unifina/service/DataUnionJoinRequestServiceIntegrationSpec.groovy
test/unit/com/unifina/service/DataUnionJoinRequestServiceSpec.groovy

Checks the dataUnionVersion from product. If the version is 2, uses Java client (DU2-alpha.1) to add the member. DUv1 functionality doesn't change.

BACK-29: Support DataUnion v2 join requests

---

Makefile
rest-e2e-tests/Makefile

- Rename test-rest to test-e2e
- Add recipes shell, ps and update
- Move e2e testing recipes to rest-e2e-tests/Makefile

Developer Tools Update 2020/11

---

grails-app/controllers/com/unifina/controller/ErrorController.groovy

Fallback reporter reports HTTP/1.0 for an unknown reason.

BACK-113: Report correct URL when logging errors

---

.travis.yml

- Do `docker build` with `--networking=host `
- Use Ubuntu 18.04 on Travis
- Prevent Docker login from storing password to Travis disk

Fix Travis Docker build

---

README.md
docs/swagger.json

Minor updates to Swagger and README

---

.github/workflows/ci-cd.yaml
.gitignore
.idea/codeStyles/Project.xml
.idea/engine-and-editor.iml
.idea/inspectionProfiles/Project_Default.xml
Makefile
README.md
grails-app/services/com/unifina/service/DataUnionService.groovy
grails-app/services/com/unifina/service/EthereumIntegrationKeyService.groovy

* Reduce "DataUnion proxy() took 30 ms" to log only if time is >=40ms and the log with warning level, otherwise use debug level
* EIKS: Pass an array of bytes (like the method expects) instead of single byte
* GA: Replace sdkman-action with setup-java
* Fix broken links in README
* Remove IntelliJ IDEA files from Git

Update DU logging and convert byte to array

---

src/groovy/com/unifina/service/ProductListParams.groovy
test/unit/com/unifina/service/ProductListParamsSpec.groovy

Type with values NORMAL and DATAUNION.

BACK-93: Add Product search parameter 'type'

---

.gitignore
.idea/engine-and-editor-grailsPlugins.iml.copy
.idea/engine-and-editor.iml.copy
.idea/sonarlint/issuestore/e/a/eab2a86bcf4b49a6d75edcbeefafedfd71d55e7c
.idea/sonarlint/issuestore/index.pb
Makefile

* Improve IDEA project file generation
* Remove Sonarlint from Git

Developer tools update 2021-02

---

rest-e2e-tests/EthereumAccount.ts
rest-e2e-tests/canvas-api.stress-test.ts
rest-e2e-tests/categories-api.test.ts
rest-e2e-tests/cors.test.ts
rest-e2e-tests/dataunions-api.test.ts
rest-e2e-tests/login-api.test.ts
rest-e2e-tests/notfound-api.test.ts
rest-e2e-tests/package-lock.json
rest-e2e-tests/package.json
rest-e2e-tests/permissions-api.stress-test.ts
rest-e2e-tests/permissions-api.test.ts
rest-e2e-tests/products-api.test.ts
rest-e2e-tests/schema-validator.ts
rest-e2e-tests/storagenode-api.test.ts
rest-e2e-tests/streamr-api-clients.ts
rest-e2e-tests/streams-api.test.ts
rest-e2e-tests/subscriptions-api.test.ts
rest-e2e-tests/test-utilities.ts
rest-e2e-tests/tsconfig.json
rest-e2e-tests/types.ts

Added also `address` field to test users (`test-utilities.ts`)

Convert REST e2e tests to TypeScript

---

grails-app/services/com/unifina/service/DataUnionJoinRequestService.groovy
test/integration/com/unifina/service/DataUnionJoinRequestServiceIntegrationSpec.groovy

Delete join request and send part message only on Data Union v1

BACK-134: Delete join request send part message

---

.github/workflows/ci-cd.yaml

* Require stress tests to pass
* Define dev tag for Docker upload
* Clean up

Update GitHub Actions

---

.github/workflows/ci-cd.yaml
Dockerfile
Makefile

* Update latest grails-builder image version
* Dont push PR's to Docker Hub
* Use Grails Builder v0.0.6
* Update slim Buster on Dockerfile
* Update Docker build/push on PR

hadolint Dockerfile

---

grails-app/migrations/core/2021-04-20-remove-canvas-dashboard-module.groovy

* Delete entries from `stream` table marked as `ui_channel`s

BACK-143: Delete streams marked as ui_channels

---

Makefile
README.md
grails-app/conf/BuildConfig.groovy
grails-app/services/com/unifina/service/ChallengeService.groovy
grails-app/services/com/unifina/service/EthereumIntegrationKeyService.groovy
src/java/com/unifina/utils/ECRecover.java
src/java/com/unifina/utils/HexIdGenerator.java
test/unit/com/unifina/service/EthereumIntegrationKeyServiceSpec.groovy
test/unit/com/unifina/utils/ECRecoverSpec.groovy

* Add tests based on old code/data
* Remove deprecated Maven Bintray repositories
* Replace deprecated Ethereum Java library with Web3j

BACK-159: Remove Bintray maven repo

---

grails-app/conf/BuildConfig.groovy

* 60 second HTTP connection timeout

BACK-166: Update Streamr Java Client v2.2.1

---

grails-app/controllers/com/unifina/controller/StorageNodeApiController.groovy
grails-app/domain/com/unifina/domain/Stream.groovy
grails-app/domain/com/unifina/domain/StreamStorageNode.groovy
grails-app/migrations/core/2021-05-14-stream-fk-storage-node.groovy
grails-app/services/com/unifina/service/StorageNodeService.groovy

stream has one to many storage nodes.

fix(storageNode): change relation to one-to-many

---

grails-app/domain/com/unifina/domain/StreamStorageNode.groovy
grails-app/services/com/unifina/service/StorageNodeService.groovy
src/java/com/unifina/service/NotifyStorageNodeTask.java

Reverts streamr-dev/core-api#1066

Revert "Remove StorageNode notification threading"

---

grails-app/conf/BuildConfig.groovy
grails-app/services/com/unifina/service/StreamrClientService.groovy
test/unit/com/unifina/service/DataUnionJoinRequestServiceSpec.groovy

Properties of class `StreamrClientOptions` have been moved to `DataUnionClientOptions`:
- dataUnionMainnetFactoryAddress
- dataUnionSidechainFactoryAddress

build: use streamr-client-java 2.3.0

---

.github/workflows/ci-cd.yaml
Makefile

Remove data-union-server

---

README.md

https://github.com/streamr-dev/core-api/runs/4687993230?check_suite_focus=true
ERROR: 1 dead links found!
46
[✖] http://grails-plugins.github.io/grails-database-migration/1.4.0/guide/single.html → Status: 404

docs: update outdated link on README

---

.github/dependabot.yaml
.github/workflows/ci-cd.yaml

ci: update workflow and Dependabot tags

---

grails-app/domain/com/streamr/core/domain/Product.groovy
grails-app/migrations/changelog.groovy
grails-app/migrations/core/2022-04-05-add-product-written-to-chain.groovy
grails-app/services/com/streamr/core/service/ProductService.groovy
src/groovy/com/streamr/core/service/ProductUpdateCommand.groovy
test/unit/com/streamr/core/service/ProductServiceSpec.groovy

Allows updating Product.chain field until product is published.

refactor: add internal field Product.writtenToChain
